# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_forum', '0002_activity_join_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='receive_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
