# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_forum', '0004_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
