# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_forum', '0005_userprofile_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
